name: Build love file

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Compress Directory
        run: |
          timestamp=$(date +%Y%m%d%H%M%S)
          zip -r LuaCraft_$timestamp.love ./*
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.1
        with:
          name: LuaCraft_$timestamp.love
          path: ./LuaCraft_$timestamp.love
