name: Build love file

on:
  push:
    branches: [ "remake-renderdistanceANDprocedurallychunkgen" ]
  pull_request:
    branches: [ "remake-renderdistanceANDprocedurallychunkgen" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Compress Directory
        run: zip -r LuaCraft.love ./*
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.1
        with:
          name: LuaCraft.love
          path: ./LuaCraft.love
